name: HideNSeek
main: Codeh\Hns\Hns
author: CodeBreak
version: 1.0.1-indev
api: [3.0.0, 3.5.2, 4.0.0]

commands:
    hns:
        usage: /hns <leave-make>
        description: Main HNS Command
    starthns:
        usage: /starthns
        description: HideNSeek force start
