engine: true

# set this to false when you are not going to add more arena, will improve performance
development-mode: true

game:
  prefix: "Hide N Seek"
  time-to-wait: 30
  time-to-play: 300
  time-to-hide: 30
  #the times are in seconds
  
reward:
  enable: true
  money: 500
  commands: []

messages:
   teamWon: "{team} won the hide and seek"
   seeker-found: "{player} found you, lmao"
   hider-found: "you found {player}"
   game-running: "sorry the game is already running"
